### PR TITLE
fix: install docker to `$env:ProgramFiles\docker`

### LINKED ISSUE #10: cli-plugins not found
By default docker binary distribution brings two cli plugins.
Those are not found, because docker searches `C:\Program Files\docker\cli-plugins\` and this packages installs them to `C:\ProgramData\chocolatey\lib\docker-engine\tools\docker\cli-plugins\`.

So i would suggest to install the docker files to `C:\Program Files\docker` by default.

I think setting the `UnzipLocation `[^1] parameter should do it.

[^1]: https://docs.chocolatey.org/en-us/create/functions/install-chocolateyzippackage#unziplocation-string

### PR DESCRIPTION
**Pull request by viceice**
- closes #10

### CODE REVIEW

**Comment by AJDurant** [comment]
Does this still shim `docker` and `docker-engine`?

**Comment by viceice** [comment]
don't know. 🤷‍♂️

**Comment by AJDurant** [comment]
Fixed in d181133, which required a fair bit of clean up alongside. Though v23 has removed the plugins anyway

**Comment by viceice** [comment]
thank you

**Pull request closed without merging**
